sudo: required
services:
  - docker

# building initial image
before_install:
  - docker build -t franksu1996/docker-react -f Dockerfile.dev .

# running tests
script:
  - docker run -e CI=true franksu1996/docker-react npm run test

# deploying to aws
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DOCKER_REACT"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-080969212246"
  bucket_path: "DOCKER_REACT"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
